"""create coaching table

Revision ID: 06aa8e769ab6
Revises: 
Create Date: 2026-02-25 19:48:37.817488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06aa8e769ab6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaching',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('courses_offered', sa.Text(), nullable=True),
    sa.Column('exam_preparation_type', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('google_maps_link', sa.Text(), nullable=True),
    sa.Column('batch_timings', sa.String(length=255), nullable=True),
    sa.Column('fees', sa.String(length=100), nullable=True),
    sa.Column('faculty_details', sa.Text(), nullable=True),
    sa.Column('reviews', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coaching_id'), 'coaching', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coaching_id'), table_name='coaching')
    op.drop_table('coaching')
    # ### end Alembic commands ###
