"""add college school mess tables

Revision ID: 18db597b1367
Revises: 06aa8e769ab6
Create Date: 2026-02-25 20:07:18.418199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18db597b1367'
down_revision: Union[str, Sequence[str], None] = '06aa8e769ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('accreditation_grade', sa.String(length=50), nullable=True),
    sa.Column('college_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('google_maps_link', sa.Text(), nullable=True),
    sa.Column('streams_available', sa.Text(), nullable=True),
    sa.Column('courses_offered', sa.Text(), nullable=True),
    sa.Column('degree_types', sa.Text(), nullable=True),
    sa.Column('fees', sa.String(length=100), nullable=True),
    sa.Column('reviews', sa.Text(), nullable=True),
    sa.Column('placement_ratio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colleges_id'), 'colleges', ['id'], unique=False)
    op.create_table('mess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('google_maps_link', sa.Text(), nullable=True),
    sa.Column('meal_types', sa.String(length=255), nullable=True),
    sa.Column('monthly_charges', sa.String(length=100), nullable=True),
    sa.Column('timing', sa.String(length=255), nullable=True),
    sa.Column('home_delivery_available', sa.Boolean(), nullable=True),
    sa.Column('hygiene_rating', sa.Float(), nullable=True),
    sa.Column('reviews', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mess_id'), 'mess', ['id'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('board', sa.String(length=100), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('accreditation_grade', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('google_maps_link', sa.Text(), nullable=True),
    sa.Column('medium_of_instruction', sa.String(length=100), nullable=True),
    sa.Column('classes_offered', sa.String(length=255), nullable=True),
    sa.Column('fees', sa.String(length=100), nullable=True),
    sa.Column('reviews', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_id'), 'schools', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schools_id'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_mess_id'), table_name='mess')
    op.drop_table('mess')
    op.drop_index(op.f('ix_colleges_id'), table_name='colleges')
    op.drop_table('colleges')
    # ### end Alembic commands ###
