"""schema changes

Revision ID: 242095c19457
Revises: 5dd0bbbfd40a
Create Date: 2026-03-04 21:36:42.542837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '242095c19457'
down_revision: Union[str, Sequence[str], None] = '5dd0bbbfd40a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organizations_id', table_name='organizations')
    op.drop_index('ix_organizations_name', table_name='organizations')
    op.drop_table('organizations')
    op.alter_column('colleges', 'type',
               existing_type=postgresql.ENUM('GOVERNMENT', 'PRIVATE', 'AUTONOMOUS', name='collegetype'),
               nullable=False)
    op.alter_column('mess', 'meal_types',
               existing_type=postgresql.ENUM('VEG', 'NON_VEG', 'BOTH', name='messtype'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mess', 'meal_types',
               existing_type=postgresql.ENUM('VEG', 'NON_VEG', 'BOTH', name='messtype'),
               nullable=True)
    op.alter_column('colleges', 'type',
               existing_type=postgresql.ENUM('GOVERNMENT', 'PRIVATE', 'AUTONOMOUS', name='collegetype'),
               nullable=True)
    op.create_table('organizations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('auth_policy', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='organizations_pkey')
    )
    op.create_index('ix_organizations_name', 'organizations', ['name'], unique=False)
    op.create_index('ix_organizations_id', 'organizations', ['id'], unique=False)
    # ### end Alembic commands ###
