"""add pg table and update hostels

Revision ID: 38dd84da3189
Revises: 18db597b1367
Create Date: 2026-02-25 20:16:23.053174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38dd84da3189'
down_revision: Union[str, Sequence[str], None] = '18db597b1367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hostels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gender_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('google_maps_link', sa.Text(), nullable=True),
    sa.Column('room_types', sa.Text(), nullable=True),
    sa.Column('facilities_available', sa.Text(), nullable=True),
    sa.Column('mess_available', sa.Boolean(), nullable=True),
    sa.Column('monthly_rent', sa.String(length=100), nullable=False),
    sa.Column('security_features', sa.Text(), nullable=True),
    sa.Column('reviews', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hostels_id'), 'hostels', ['id'], unique=False)
    op.create_table('pg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gender_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('google_maps_link', sa.Text(), nullable=True),
    sa.Column('room_types', sa.Text(), nullable=True),
    sa.Column('one_month_rent', sa.String(length=100), nullable=False),
    sa.Column('food_included', sa.Boolean(), nullable=True),
    sa.Column('facilities_available', sa.Text(), nullable=True),
    sa.Column('security_features', sa.Text(), nullable=True),
    sa.Column('reviews', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pg_id'), 'pg', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pg_id'), table_name='pg')
    op.drop_table('pg')
    op.drop_index(op.f('ix_hostels_id'), table_name='hostels')
    op.drop_table('hostels')
    # ### end Alembic commands ###
