"""increase phone length

Revision ID: 5dd0bbbfd40a
Revises: f3920ef68529
Create Date: 2026-03-04 21:27:28.859874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dd0bbbfd40a'
down_revision: Union[str, Sequence[str], None] = 'f3920ef68529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organizations_id', table_name='organizations')
    op.drop_index('ix_organizations_name', table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_coaching_id', table_name='coaching')
    op.drop_table('coaching')
    op.drop_index('ix_pg_id', table_name='pg')
    op.drop_table('pg')
    op.add_column('colleges', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('colleges', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # altering a text column to an enum requires an explicit USING cast on
    # PostgreSQL. the autogenerated `alter_column` call fails with
    # "column \"type\" cannot be cast automatically to type collegetype".
    # perform the change via raw SQL so we can specify the cast expression.
    op.execute(
        "ALTER TABLE colleges ALTER COLUMN type TYPE collegetype "
        "USING type::collegetype"
    )
    op.alter_column('colleges', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('colleges', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
    op.create_index(op.f('ix_colleges_accreditation_grade'), 'colleges', ['accreditation_grade'], unique=False)
    op.create_index(op.f('ix_colleges_college_code'), 'colleges', ['college_code'], unique=True)
    op.create_index(op.f('ix_colleges_established_year'), 'colleges', ['established_year'], unique=False)
    op.create_index(op.f('ix_colleges_name'), 'colleges', ['name'], unique=True)
    op.create_index(op.f('ix_colleges_phone_number'), 'colleges', ['phone_number'], unique=False)
    op.create_index(op.f('ix_colleges_type'), 'colleges', ['type'], unique=False)
    op.add_column('hostels', sa.Column('gender', sa.Enum('BOYS', 'GIRLS', 'CO_ED', name='gendertype'), nullable=False))
    op.add_column('hostels', sa.Column('room_type', sa.Enum('SINGLE', 'DOUBLE', 'TRIPLE', name='roomtype'), nullable=False))
    op.add_column('hostels', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('hostels', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('hostels', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('hostels', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('hostels', 'mess_available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_hostels_email'), 'hostels', ['email'], unique=True)
    op.create_index(op.f('ix_hostels_gender'), 'hostels', ['gender'], unique=False)
    op.create_index(op.f('ix_hostels_name'), 'hostels', ['name'], unique=True)
    op.create_index(op.f('ix_hostels_phone_number'), 'hostels', ['phone_number'], unique=False)
    op.create_index(op.f('ix_hostels_room_type'), 'hostels', ['room_type'], unique=False)
    op.drop_constraint('hostels_mess_id_fkey', 'hostels', type_='foreignkey')
    op.create_foreign_key(None, 'hostels', 'mess', ['mess_id'], ['id'], ondelete='SET NULL')
    op.drop_column('hostels', 'reviews')
    op.add_column('mess', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('mess', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('mess', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('mess', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
    # similar to colleges.type above, changing a text field to an enum
    # requires a USING clause so Postgres knows how to cast existing values.
    op.execute(
        "ALTER TABLE mess ALTER COLUMN meal_types TYPE messtype "
        "USING meal_types::messtype"
    )
    op.alter_column('mess', 'home_delivery_available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_mess_meal_types'), 'mess', ['meal_types'], unique=False)
    op.create_index(op.f('ix_mess_name'), 'mess', ['name'], unique=True)
    op.create_index(op.f('ix_mess_phone_number'), 'mess', ['phone_number'], unique=False)
    op.drop_column('mess', 'reviews')
    op.alter_column('pgs', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.add_column('reviews', sa.Column('college_id', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('school_id', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('hostel_id', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('mess_id', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('coaching_id', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('reviews', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_reviews_coaching_id'), 'reviews', ['coaching_id'], unique=False)
    op.create_index(op.f('ix_reviews_college_id'), 'reviews', ['college_id'], unique=False)
    op.create_index(op.f('ix_reviews_hostel_id'), 'reviews', ['hostel_id'], unique=False)
    op.create_index(op.f('ix_reviews_mess_id'), 'reviews', ['mess_id'], unique=False)
    op.create_index(op.f('ix_reviews_school_id'), 'reviews', ['school_id'], unique=False)
    op.drop_constraint('reviews_user_id_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'hostels', ['hostel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'coachings', ['coaching_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'mess', ['mess_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reviews', 'entity_id')
    op.drop_column('reviews', 'entity_type')
    op.add_column('schools', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('schools', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('schools', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('schools', 'type',
               existing_type=postgresql.ENUM('GOVERNMENT', 'PRIVATE', name='schooltype'),
               nullable=False)
    op.alter_column('schools', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('schools', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
    op.create_index(op.f('ix_schools_accreditation_grade'), 'schools', ['accreditation_grade'], unique=False)
    op.create_index(op.f('ix_schools_board'), 'schools', ['board'], unique=False)
    op.create_index(op.f('ix_schools_email'), 'schools', ['email'], unique=True)
    op.create_index(op.f('ix_schools_established_year'), 'schools', ['established_year'], unique=False)
    op.create_index(op.f('ix_schools_name'), 'schools', ['name'], unique=True)
    op.create_index(op.f('ix_schools_phone_number'), 'schools', ['phone_number'], unique=False)
    op.create_index(op.f('ix_schools_type'), 'schools', ['type'], unique=False)
    # convert role enum; the source type is still the old postgres enum
    # "userrole" which cannot be coerced directly to the new name. cast
    # through text first so Postgres will accept the conversion.
    op.execute(
        "ALTER TABLE users ALTER COLUMN role TYPE user_role_enum "
        "USING role::text::user_role_enum"
    )
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'USER', name='user_role_enum'),
               type_=postgresql.ENUM('ADMIN', 'USER', name='userrole'),
               existing_nullable=False)
    op.drop_index(op.f('ix_schools_type'), table_name='schools')
    op.drop_index(op.f('ix_schools_phone_number'), table_name='schools')
    op.drop_index(op.f('ix_schools_name'), table_name='schools')
    op.drop_index(op.f('ix_schools_established_year'), table_name='schools')
    op.drop_index(op.f('ix_schools_email'), table_name='schools')
    op.drop_index(op.f('ix_schools_board'), table_name='schools')
    op.drop_index(op.f('ix_schools_accreditation_grade'), table_name='schools')
    op.alter_column('schools', 'phone_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('schools', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('schools', 'type',
               existing_type=postgresql.ENUM('GOVERNMENT', 'PRIVATE', name='schooltype'),
               nullable=True)
    op.drop_column('schools', 'is_active')
    op.drop_column('schools', 'updated_at')
    op.drop_column('schools', 'created_at')
    op.add_column('reviews', sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_user_id_fkey', 'reviews', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_reviews_school_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_mess_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_hostel_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_college_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_coaching_id'), table_name='reviews')
    op.alter_column('reviews', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('reviews', 'is_active')
    op.drop_column('reviews', 'updated_at')
    op.drop_column('reviews', 'coaching_id')
    op.drop_column('reviews', 'mess_id')
    op.drop_column('reviews', 'hostel_id')
    op.drop_column('reviews', 'school_id')
    op.drop_column('reviews', 'college_id')
    op.alter_column('pgs', 'phone_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.add_column('mess', sa.Column('reviews', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_mess_phone_number'), table_name='mess')
    op.drop_index(op.f('ix_mess_name'), table_name='mess')
    op.drop_index(op.f('ix_mess_meal_types'), table_name='mess')
    op.alter_column('mess', 'home_delivery_available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('mess', 'meal_types',
               existing_type=sa.Enum('VEG', 'NON_VEG', 'BOTH', name='messtype'),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mess', 'phone_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('mess', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('mess', 'updated_at')
    op.drop_column('mess', 'created_at')
    op.add_column('hostels', sa.Column('reviews', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'hostels', type_='foreignkey')
    op.create_foreign_key('hostels_mess_id_fkey', 'hostels', 'mess', ['mess_id'], ['id'])
    op.drop_index(op.f('ix_hostels_room_type'), table_name='hostels')
    op.drop_index(op.f('ix_hostels_phone_number'), table_name='hostels')
    op.drop_index(op.f('ix_hostels_name'), table_name='hostels')
    op.drop_index(op.f('ix_hostels_gender'), table_name='hostels')
    op.drop_index(op.f('ix_hostels_email'), table_name='hostels')
    op.alter_column('hostels', 'mess_available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('hostels', 'phone_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('hostels', 'is_active')
    op.drop_column('hostels', 'updated_at')
    op.drop_column('hostels', 'created_at')
    op.drop_column('hostels', 'room_type')
    op.drop_column('hostels', 'gender')
    op.drop_index(op.f('ix_colleges_type'), table_name='colleges')
    op.drop_index(op.f('ix_colleges_phone_number'), table_name='colleges')
    op.drop_index(op.f('ix_colleges_name'), table_name='colleges')
    op.drop_index(op.f('ix_colleges_established_year'), table_name='colleges')
    op.drop_index(op.f('ix_colleges_college_code'), table_name='colleges')
    op.drop_index(op.f('ix_colleges_accreditation_grade'), table_name='colleges')
    op.alter_column('colleges', 'phone_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('colleges', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('colleges', 'type',
               existing_type=sa.Enum('GOVERNMENT', 'PRIVATE', 'AUTONOMOUS', name='collegetype'),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('colleges', 'updated_at')
    op.drop_column('colleges', 'created_at')
    op.create_table('pg',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('google_maps_link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('one_month_rent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('food_included', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('facilities_available', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('security_features', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reviews', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pg_pkey')
    )
    op.create_index('ix_pg_id', 'pg', ['id'], unique=False)
    op.create_table('coaching',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('established_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('courses_offered', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('exam_preparation_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('google_maps_link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('batch_timings', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fees', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('faculty_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reviews', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='coaching_pkey')
    )
    op.create_index('ix_coaching_id', 'coaching', ['id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('auth_policy', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='organizations_pkey')
    )
    op.create_index('ix_organizations_name', 'organizations', ['name'], unique=False)
    op.create_index('ix_organizations_id', 'organizations', ['id'], unique=False)
    # ### end Alembic commands ###
