"""add_user_settings_fields

Revision ID: 9fc4a2c83eef
Revises: c8119c923063
Create Date: 2026-04-01 14:34:54.900622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc4a2c83eef'
down_revision: Union[str, Sequence[str], None] = 'c8119c923063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location_access', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('dark_mode', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('preferred_language', sa.String(length=50), server_default='English', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'dark_mode')
    op.drop_column('users', 'location_access')
    # ### end Alembic commands ###
