"""support reviews for school and college

Revision ID: abf2cad0835f
Revises: 6060b65048f0
Create Date: 2026-02-27 17:00:10.341668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf2cad0835f'
down_revision: Union[str, Sequence[str], None] = '6060b65048f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('school_id', sa.Integer(), nullable=True))
    op.alter_column('reviews', 'college_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'reviews', 'schools', ['school_id'], ['id'])
    op.drop_column('schools', 'reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('reviews', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.alter_column('reviews', 'college_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('reviews', 'school_id')
    # ### end Alembic commands ###
