"""polymorphic review system

Revision ID: fd21b7514670
Revises: abf2cad0835f
Create Date: 2026-02-27 17:09:38.499143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd21b7514670'
down_revision: Union[str, Sequence[str], None] = 'abf2cad0835f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostels', sa.Column('mess_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hostels', 'mess', ['mess_id'], ['id'])
    op.add_column('reviews', sa.Column('entity_type', sa.String(length=50), nullable=False))
    op.add_column('reviews', sa.Column('entity_id', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('reviews_school_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_college_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'])
    op.drop_column('reviews', 'college_id')
    op.drop_column('reviews', 'school_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('college_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_college_id_fkey'), 'reviews', 'colleges', ['college_id'], ['id'])
    op.create_foreign_key(op.f('reviews_school_id_fkey'), 'reviews', 'schools', ['school_id'], ['id'])
    op.drop_column('reviews', 'user_id')
    op.drop_column('reviews', 'entity_id')
    op.drop_column('reviews', 'entity_type')
    op.drop_constraint(None, 'hostels', type_='foreignkey')
    op.drop_column('hostels', 'mess_id')
    # ### end Alembic commands ###
